### ISSUE TITLE
Fresh Install - Process Exit Code 1

### ISSUE THREAD

**Issue by redleeder** [Jomik/screeps-server#218]
I am working on setting up a fresh instance of screeps-server and am running into issues getting up and running. The screeps container gets stuck in the following process, start, exit, restart loop.

**screeps logs**
```
Updating dependencies
No dependency changes
Done updating
Writing mods configuration
Mods have been configured
All mods are up to date!
Server version 4.2.19
Starting all processes. Ports: 21025 (game), 21026 (cli)
[storage] process 30 started
[backend] process 41 started
[engine_main] process 42 started
[engine_runner1] process 48 started
[engine_processor1] process 55 started
[engine_processor2] process 62 started
[engine_processor3] process 68 started
[engine_processor4] process 81 started
[engine_processor5] process 85 started
[engine_processor6] process 90 started
[engine_processor5] process 85 exited with code 1, restarting...
[engine_processor6] process 90 exited with code 1, restarting...
[engine_processor5] process 155 started
[engine_processor6] process 166 started
[engine_main] process 42 exited with code 1, restarting...
[engine_processor2] process 62 exited with code 1, restarting...
[backend] process 41 exited with code 0, restarting...
[engine_processor1] process 55 exited with code 1, restarting...
[engine_runner1] process 48 exited with code 1, restarting...
[engine_processor4] process 81 exited with code 1, restarting...
[engine_processor3] process 68 exited with code 1, restarting...
```

**mongo logs**
Have a whole slew of error messages, this is just a snippet

```
t={"$date":"2025-03-04T15:47:41.512+00:00"} s=I c=- id=20520 ctx=initandlisten msg=Stopping further Flow Control ticket acquisitions.
t={"$date":"2025-03-04T15:47:41.512+00:00"} s=I c=STORAGE id=4784908 ctx=initandlisten msg=Shutting down the PeriodicThreadToAbortExpiredTransactions
t={"$date":"2025-03-04T15:47:41.512+00:00"} s=I c=STORAGE id=4784934 ctx=initandlisten msg=Shutting down the PeriodicThreadToDecreaseSnapshotHistoryCachePressure
t={"$date":"2025-03-04T15:47:41.512+00:00"} s=I c=REPL id=4784909 ctx=initandlisten msg=Shutting down the ReplicationCoordinator
t={"$date":"2025-03-04T15:47:41.512+00:00"} s=I c=SHARDING id=4784910 ctx=initandlisten msg=Shutting down the ShardingInitializationMongoD
t={"$date":"2025-03-04T15:47:41.512+00:00"} s=I c=REPL id=4784911 ctx=initandlisten msg=Enqueuing the ReplicationStateTransitionLock for shutdown
t={"$date":"2025-03-04T15:47:41.512+00:00"} s=I c=- id=4784912 ctx=initandlisten msg=Killing all operations for shutdown
t={"$date":"2025-03-04T15:47:41.512+00:00"} s=I c=- id=4695300 ctx=initandlisten msg=Interrupted all currently running operations attr={"opsKilled":3}
t={"$date":"2025-03-04T15:47:41.512+00:00"} s=I c=COMMAND id=4784913 ctx=initandlisten msg=Shutting down all open transactions
t={"$date":"2025-03-04T15:47:41.512+00:00"} s=I c=REPL id=4784914 ctx=initandlisten msg=Acquiring the ReplicationStateTransitionLock for shutdown
t={"$date":"2025-03-04T15:47:41.512+00:00"} s=I c=INDEX id=4784915 ctx=initandlisten msg=Shutting down the IndexBuildsCoordinator
t={"$date":"2025-03-04T15:47:41.512+00:00"} s=I c=REPL id=4784916 ctx=initandlisten msg=Reacquiring the ReplicationStateTransitionLock for shutdown
t={"$date":"2025-03-04T15:47:41.512+00:00"} s=I c=REPL id=4784917 ctx=initandlisten msg=Attempting to mark clean shutdown
t={"$date":"2025-03-04T15:47:41.512+00:00"} s=I c=NETWORK id=4784918 ctx=initandlisten msg=Shutting down the ReplicaSetMonitor
t={"$date":"2025-03-04T15:47:41.512+00:00"} s=I c=SHARDING id=4784921 ctx=initandlisten msg=Shutting down the MigrationUtilExecutor
t={"$date":"2025-03-04T15:47:41.512+00:00"} s=I c=CONTROL id=4784925 ctx=initandlisten msg=Shutting down free monitoring
```

**My Docker Compose section**
```yaml
volumes:
  screeps-data:
  screeps-mods:
  redis-data:
  mongo-data:

# Screeps
  screeps:
    container_name: screeps
    image: ghcr.io/jomik/screeps-server:edge
    depends_on:
      - mongo
      - redis
    ports:
      - 21025:21025/tcp
    volumes:
      # ./home/redleeder/Docker/screeps/config.yml:/screeps/config.yml
      # /home/redleeder/Docker/screeps/config.yml:/screeps/config.yml
      - ./screeps/config.yml:/screeps/config.yml
      - screeps-data:/data
      - screeps-mods:/screeps/mods
    environment:
      MONGO_HOST: mongo
      REDIS_HOST: redis
      STEAM_KEY: <<STEAM API KEY HERE>>
    restart: unless-stopped
    build: server

  mongo:
    container_name: screeps_mongo
    image: mongo:4.4.18
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  redis:
    container_name: screeps_redis
    image: redis:7
    volumes:
      - redis-data:/data
    restart: unless-stopped
```

My Config located in ./screeps/config.yaml
```yaml
mods:
  - screepsmod-auth
  - screepsmod-admin-utils
  - screepsmod-mongo
bots:
  simplebot: screepsbot-zeswarm

launcherOptions:
  # If set, automatically ensures all mods are updated
  autoUpdate: false
  # If set, forward console messages to terminal
  logConsole: false
```

I've also tried the other volume mounts listed in the compose above but got the following error

```
    throw err;
    ^
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:498:3)
    at tryReadSync (fs.js:332:20)
    at Object.readFileSync (fs.js:369:19)
    at Object.<anonymous> (/screeps/bin/start:25:52)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
```

**Comment by Jomik** [comment]
Interesting!

It seems like your `docker-compose.yml` is incomplete. But I suspect that's because you edited to add it here. It's missing the `services` key.
Is the `./screeps/config.yml` relative to your `docker-compose.yml`? So that would be at `./docker-compose.yml`?

Perhaps you can try with `ghcr.io/jomik/screeps-server:edge-node12`, `ghcr.io/jomik/screeps-server:sha-d1ae937` and `ghcr.io/jomik/screeps-server:sha-d1ae937-node12`

I do suspect that it's the mounting of `config.yml` that is wrong somehow, as that would usually result in a directory called `/screeps/config.yml` which results in that error 🤔

**Comment by redleeder** [comment]
Yeah this is part of a much larger docker compose file (really ought to reorganize mine into modular pieces at some point). And yeah you can see I was jumping all over the place on the config volume mount though I'm fairly certain `./screeps/config.yml:/screeps/config.yml` is the proper mount syntax with my folder structure.

```
/home/redleeder/Docker/docker-compose.yml
/home/redleeder/Docker/screeps/config.yml
```

Still getting the exited with code 1 restart issue

**Comment by Jomik** [comment]
Can we try to open a shell in the screeps container? That should allow you to investigate the log files that the screeps server spits out.
I believe you may get this error from an invalid Steam key as well, can you verify that it is correct and visible in the container? And perhaps investigate the log files in the `/screeps/logs` folder (IIRC)
Are you in the Screeps discord, it may be easier to get help there, as I am sadly quite inactive in Screeps currently.

**Comment by redleeder** [comment]
The steam key is correct (does the domain name matter when creating the key?).

Logs all spit out the same thing for whatever reason (backend.log, engine_main.log, engine_processor1.log, etc)
```
Loading mods from "/screeps/mods.json"
 - /screeps/mods/node_modules/screepsmod-admin-utils/index.js
 - /screeps/mods/node_modules/screepsmod-auth/index.js
 - /screeps/mods/node_modules/screepsmod-mongo/index.js
(node:69194) [MONGODB DRIVER] Warning: the options [uri] is not supported
```

If this doesn't ring any bells for ya I can troubleshoot on the discord server. Appreciate your help though and the project!

**Comment by Jomik** [comment]
This all looks fine! I come up blank, sadly.
I know there's a few using the server on the Screeps discord, feel free to tag me there too if needed, but I think there's a higher chance to get it resolved there - then please update this with the solution 😄

**Comment by redleeder** [comment]
So the culprit was mongo versioning. This could very well be a 'me' issue and not a screeps-server issue

**Mongo Log**
```
s=F c=CONTROL id=20573 ctx=initandlisten msg=Wrong mongod version attr={"error":"UPGRADE PROBLEM: Found an invalid featureCompatibilityVersion document (ERROR: BadValue: Invalid value for version, found 8.0, expected '4.4' or '4.2'. Contents of featureCompatibilityVersion document in admin.system.version: { _id: \"featureCompatibilityVersion\", version: \"8.0\" }. See https://docs.mongodb.com/master/release-notes/4.4-compatibility/#feature-compatibility.).
```

Upgrading my mongo db version to 8.0 got me up and running!

```
  mongo:
    container_name: mongo
    image: **mongo:8.0**
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
```
