### ISSUE TITLE
Different VM runtime from official servers

### ISSUE THREAD

**Issue by tim101010101** [Jomik/screeps-server#227]
Hey, thanks for your work first, it really saved my life!

I found that the VM runtime is maybe difference from the official server, is it expected?

Here is my code

```js
module.exports.loop = () => {
  console.log(undefined ?? 1) // notice this "??"
}
```

I deployed it on my private server, and got an `SyntaxError` like this

![Image](https://github.com/user-attachments/assets/506c315b-452c-45dc-824d-f0ffe86e0517)

But it works well on official (SIM server to be precise)

![Image](https://github.com/user-attachments/assets/3c8fca02-0d50-4b2d-801f-ce20d2bb1518)

`??` is NOT necessary for me, I just want to know if there are other inconsistent behaviors

And here is my `docker-compose.yml`

```yml
services:
  screeps:
    image: ghcr.io/jomik/screeps-server:sha-c2d852f-node12
    depends_on:
      - mongo
      - redis
    ports:
      - 21025:21025/tcp
    volumes:
      - ./config.yml:/screeps/config.yml
      - screeps-data:/data
      - screeps-mods:/screeps/mods
    environment:
      MONGO_HOST: mongo
      REDIS_HOST: redis
      STEAM_KEY: ${STEAM_KEY:?"Missing steam key"}
    restart: unless-stopped
    build: server

  mongo:
    image: mongo:4.4.18
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  screeps-data:
  screeps-mods:
  redis-data:
  mongo-data:
```
